n1 = input('Digite um número ')
n2 = input('Digite um número ')
result = int(n1)+int(n2)
# print('O resultado é', result)
# print('O resultado é {}'.format(result))
# print('A soma entre', n1, ' e', n2, 'vale', result)
print('A soma entre {} e {} vale {}!'.format(n1, n2, result))
